### PR TITLE
Pad 0 if the digit is 1

### PR DESCRIPTION
**Pull request by wozaki**
SPBS sometimes passes 1 digit date and we can't register Google Calendar Event with the 1 digit date.

example
```
◆日時 
・2018年8月20日（月）0:15 ～ 6:00（※24時間表記） 
・2018年8月27日（月）0:15 ～ 6:00（※24時間表記） 
```

### CODE REVIEW

**Comment by wozaki** [comment]
@ohbarye @kyanny @kachick @rivayama @yuya-takeyama 
Please review and merge 🙏

**Comment by wozaki** [comment]
@ohbarye @kyanny @kachick @rivayama @yuya-takeyama
Please review and merge 🙏

**Review by kachick — APPROVED** [review]
LGTM 👍

**Comment by wozaki** [comment]
Thanks ☺️

**Pull request merged**
