### PR TITLE
Relax parser to allow their typo

### PR DESCRIPTION
**Pull request by kachick**
Basically they write the title as

```
~　メンテナンスのご連絡
```

But I have faced another pattern...

```
~　メンテナンスのご連絡 
```

Please drag 🐭 around the line end

### CODE REVIEW

**Comment by tanaka51** [comment]
Great catch...!! LGTM!!

**Comment by kyanny** [comment]
Thank you very much!

**Comment by kachick** [comment]
Thank you!

**Comment by kyanny** [comment]
@banyan @kachick @yuya-takeyama @ohbarye @wozaki @rivayama @tanaka51 
I've set you collaborator of this repo. Next time feel free to review/merge without waiting me, as always!

**Pull request merged**
